PACKAGE_NAME="snd-soc-tas2783-sdw-px13"
PACKAGE_VERSION="1.0"
BUILT_MODULE_NAME[0]="snd-soc-tas2783-sdw"
DEST_MODULE_LOCATION[0]="/updates"
MAKE[0]="make KVER=${kernelver} LLVM=1"
CLEAN="make KVER=${kernelver} LLVM=1 clean"
AUTOINSTALL="yes"
